name: Pull Request CI

run-name: PR validator

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-validator:
    runs-on: ubuntu-latest

    steps:
    - name: Use PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install

    - name: Run unit tests
      run: vendor/bin/phpunit

    - name: Execute PHP Code Sniffer
      run: vendor/bin/grumphp run --tasks phpcs

    - name: Execute PHP Mess Detector
      run: vendor/bin/grumphp run --tasks phpmd
